version: "2"

services:
  app:
    build: .
    volumes:
      - "$HOME/.ssh:/tmp/host-ssh"
      - "$PWD:/app"
    environment:
      DB_HOST: arts_sciences_portal-psql
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_DATABASE: dev
      PORT: 4000
    networks:
      - internal
    ports:
      - "4000:4000"
    links:
      - postgres
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]

  postgres:
    image: postgres:9.6
    container_name: arts_sciences_portal-psql
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      - internal
#    ports:
#      - "5432:5432"

networks:
  internal:
