version: "2"

services:
  app:
    build: .
    volumes:
      - "$HOME/.ssh:/tmp/host-ssh"
      - "$PWD:/app"
    environment:
      DB_HOST: arts_sciences_portal-sql
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_DATABASE: dev
      DB_PORT: 3306
      PORT: 4000
    networks:
      - internal
    ports:
      - "4000:4000"
    links:
      - mysql
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]

  mysql:
    image: mysql:5.7
    container_name: arts_sciences_portal-sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dev
    networks:
      - internal
#    ports:
#      - "5432:5432"


networks:
  internal:
